### ISSUE TITLE
Autoscale and click event

### ISSUE THREAD

**Issue by nikpundik** [vsmode/pixel8#1]
The AutoScale wrapper is adding a transform scale (< 1.0) if the stage doesn't fit in the container, leading a wrong onClick cell detection (because the provided scale value should take in account also the AutoScale transformation).

**Comment by jozanza** [comment]
Alright — the first issue! :D

Good find @nikpundik. I noticed you forked the repo. Do you plan on submitting a PR to fix this issue, or shall I take a look?

**Comment by nikpundik** [comment]
Is there a way to get the scale value from the AutoScale component? Mhm, I guess no..Alternatively removing the AutoScale can fix the problem but will lead to overflow-x.

Do you have any ideas?

**Comment by nikpundik** [comment]
Ok, I think I found a solution, I'm submitting a PR

**Comment by jozanza** [comment]
Your fix looks good to me! I’ll merge and deploy an update later today. Thanks @nikpundik 👌🎉
